// Full 78-card tarot deck (Rider-Waite-Smith tradition)
// Each card: id, name, arcana, suit (minor only), number (minor only),
// keywords, upright meaning, reversedMeaning.
// Meanings are concise prompts intended to be passed to an LLM as grounding.

export interface Card {
  id: number;
  name: string;
  arcana: 'major' | 'minor';
  suit?: 'wands' | 'cups' | 'swords' | 'pentacles';
  number?: number;
  keywords: string[];
  upright: string;
  reversedMeaning: string;
}

export interface DrawnCard extends Card {
  isReversed: boolean;
}

export const cards: Card[] = [
  // ===== MAJOR ARCANA (22) =====
  { id: 0,  name: 'The Fool',            arcana: 'major', keywords: ['new beginnings', 'innocence', 'spontaneity', 'leap of faith'], upright: 'Fresh starts, open possibility, embracing the unknown with optimism and trust.', reversedMeaning: 'Recklessness, naivety, hesitation to begin, fear of the unknown.' },
  { id: 1,  name: 'The Magician',        arcana: 'major', keywords: ['manifestation', 'willpower', 'skill', 'action'], upright: 'You have the tools and ability to make something real. Focused will turns intention into outcome.', reversedMeaning: 'Manipulation, untapped potential, scattered focus, illusion.' },
  { id: 2,  name: 'The High Priestess',  arcana: 'major', keywords: ['intuition', 'mystery', 'subconscious', 'inner voice'], upright: 'Trust your inner knowing. Hidden truths are surfacing; listen rather than act.', reversedMeaning: 'Ignored intuition, secrets surfacing, disconnection from inner wisdom.' },
  { id: 3,  name: 'The Empress',         arcana: 'major', keywords: ['nurture', 'abundance', 'creativity', 'fertility'], upright: 'Creative abundance, nurturing energy, growth in body, home, or projects.', reversedMeaning: 'Creative block, dependence, neglect of self or others, smothering.' },
  { id: 4,  name: 'The Emperor',         arcana: 'major', keywords: ['authority', 'structure', 'control', 'stability'], upright: 'Order, leadership, the power that comes from clear structure and discipline.', reversedMeaning: 'Rigidity, domination, abuse of power, lack of self-control.' },
  { id: 5,  name: 'The Hierophant',      arcana: 'major', keywords: ['tradition', 'institutions', 'teaching', 'convention'], upright: 'Established systems, mentorship, working within shared values and traditions.', reversedMeaning: 'Rebellion against convention, dogma, restrictive beliefs that no longer serve.' },
  { id: 6,  name: 'The Lovers',          arcana: 'major', keywords: ['partnership', 'choice', 'alignment', 'values'], upright: 'A meaningful union or a values-aligned choice. Harmony between two forces.', reversedMeaning: 'Disharmony, misaligned values, a difficult choice, broken trust.' },
  { id: 7,  name: 'The Chariot',         arcana: 'major', keywords: ['willpower', 'determination', 'victory', 'control'], upright: 'Forward momentum through focused will. Opposing forces harnessed toward one goal.', reversedMeaning: 'Loss of direction, lack of control, opposing forces pulling you apart.' },
  { id: 8,  name: 'Strength',            arcana: 'major', keywords: ['courage', 'patience', 'compassion', 'inner power'], upright: 'Quiet strength, mastery through gentleness and patience rather than force.', reversedMeaning: 'Self-doubt, weakness, raw force without discipline, insecurity.' },
  { id: 9,  name: 'The Hermit',          arcana: 'major', keywords: ['solitude', 'introspection', 'seeking', 'wisdom'], upright: 'Withdraw to find answers within. A period of reflection brings clarity.', reversedMeaning: 'Isolation, loneliness, withdrawal that has gone too far, refusal to seek.' },
  { id: 10, name: 'Wheel of Fortune',    arcana: 'major', keywords: ['cycles', 'change', 'fate', 'turning points'], upright: 'The wheel turns. A shift in fortune, the larger pattern of your life moving forward.', reversedMeaning: 'Bad luck, resistance to change, feeling stuck in a downward cycle.' },
  { id: 11, name: 'Justice',             arcana: 'major', keywords: ['fairness', 'truth', 'cause and effect', 'accountability'], upright: 'Truth comes out, balance is restored, decisions are made with clear eyes.', reversedMeaning: 'Unfairness, dishonesty, avoiding accountability, biased judgment.' },
  { id: 12, name: 'The Hanged Man',      arcana: 'major', keywords: ['surrender', 'new perspective', 'pause', 'letting go'], upright: 'A pause that reveals a new angle. Surrender to gain insight; struggle no longer serves.', reversedMeaning: 'Stalling, martyrdom, unnecessary sacrifice, refusal to see differently.' },
  { id: 13, name: 'Death',               arcana: 'major', keywords: ['endings', 'transformation', 'transition', 'release'], upright: 'An ending that clears space for what comes next. Necessary transformation.', reversedMeaning: 'Resistance to change, clinging to what has ended, fear of transition.' },
  { id: 14, name: 'Temperance',          arcana: 'major', keywords: ['balance', 'moderation', 'patience', 'blending'], upright: 'Patient blending of opposites. Moderation produces something greater than its parts.', reversedMeaning: 'Imbalance, excess, impatience, conflict between competing desires.' },
  { id: 15, name: 'The Devil',           arcana: 'major', keywords: ['bondage', 'addiction', 'shadow', 'materialism'], upright: 'Attachments and patterns that hold you. The chains are looser than they appear.', reversedMeaning: 'Breaking free, releasing limiting beliefs, reclaiming your power.' },
  { id: 16, name: 'The Tower',           arcana: 'major', keywords: ['sudden change', 'upheaval', 'revelation', 'collapse'], upright: 'A sudden disruption that shatters a false structure. Painful but clarifying.', reversedMeaning: 'Avoiding disaster, fear of change, a slow collapse you sense but resist.' },
  { id: 17, name: 'The Star',            arcana: 'major', keywords: ['hope', 'renewal', 'inspiration', 'calm'], upright: 'Healing after hardship. Quiet hope, renewed faith, a guiding light returning.', reversedMeaning: 'Loss of faith, despair, disconnection from hope or purpose.' },
  { id: 18, name: 'The Moon',            arcana: 'major', keywords: ['illusion', 'intuition', 'uncertainty', 'dreams'], upright: 'Things are not as they seem. Trust intuition over appearances; navigate by feel.', reversedMeaning: 'Confusion clearing, secrets revealed, anxiety releasing.' },
  { id: 19, name: 'The Sun',             arcana: 'major', keywords: ['joy', 'success', 'vitality', 'clarity'], upright: 'Warmth, success, the simple joy of being seen and alive. Things go well.', reversedMeaning: 'Temporary sadness, dimmed joy, delayed success, false optimism.' },
  { id: 20, name: 'Judgement',           arcana: 'major', keywords: ['awakening', 'reckoning', 'calling', 'rebirth'], upright: 'A wake-up call. Past chapters reviewed, a clear calling to step into something new.', reversedMeaning: 'Self-doubt, ignoring the call, harsh self-judgment, refusal to evolve.' },
  { id: 21, name: 'The World',           arcana: 'major', keywords: ['completion', 'wholeness', 'achievement', 'integration'], upright: 'A cycle completes. Wholeness, accomplishment, the satisfaction of arrival.', reversedMeaning: 'Incompletion, lack of closure, a goal nearly reached but not quite.' },

  // ===== WANDS (passion, creativity, action, spirit) =====
  { id: 22, name: 'Ace of Wands',     arcana: 'minor', suit: 'wands', number: 1,  keywords: ['inspiration', 'spark', 'new energy', 'potential'], upright: 'A creative spark, the first surge of inspiration or passion for something new.', reversedMeaning: 'Delays, lack of motivation, a spark that fizzles, creative block.' },
  { id: 23, name: 'Two of Wands',     arcana: 'minor', suit: 'wands', number: 2,  keywords: ['planning', 'decisions', 'future', 'personal power'], upright: 'Surveying the territory and planning the next move. Power held in potential.', reversedMeaning: 'Fear of the unknown, playing it safe, scattered planning.' },
  { id: 24, name: 'Three of Wands',   arcana: 'minor', suit: 'wands', number: 3,  keywords: ['expansion', 'foresight', 'progress', 'ships coming in'], upright: 'Plans are in motion; results are on the horizon. Look outward and forward.', reversedMeaning: 'Delays, obstacles to expansion, narrow vision, unmet expectations.' },
  { id: 25, name: 'Four of Wands',    arcana: 'minor', suit: 'wands', number: 4,  keywords: ['celebration', 'harmony', 'homecoming', 'milestones'], upright: 'A milestone worth celebrating. Community, belonging, joyful arrival.', reversedMeaning: 'Tension at home, postponed celebration, feeling out of place.' },
  { id: 26, name: 'Five of Wands',    arcana: 'minor', suit: 'wands', number: 5,  keywords: ['conflict', 'competition', 'tension', 'scrappy energy'], upright: 'Friction with others, competing voices, productive (or wasteful) conflict.', reversedMeaning: 'Avoiding conflict, inner tension, conflict resolving.' },
  { id: 27, name: 'Six of Wands',     arcana: 'minor', suit: 'wands', number: 6,  keywords: ['victory', 'recognition', 'success', 'pride'], upright: 'Public recognition, a win that others see. Earned confidence.', reversedMeaning: 'Lack of recognition, ego, private success that goes unseen, fall from grace.' },
  { id: 28, name: 'Seven of Wands',   arcana: 'minor', suit: 'wands', number: 7,  keywords: ['defense', 'perseverance', 'standing ground', 'challenge'], upright: 'Defending your position against challenge. Hold your ground; you have the higher footing.', reversedMeaning: 'Overwhelm, giving up, feeling outnumbered, defensive exhaustion.' },
  { id: 29, name: 'Eight of Wands',   arcana: 'minor', suit: 'wands', number: 8,  keywords: ['speed', 'movement', 'messages', 'swift action'], upright: 'Things move quickly. News arrives, momentum builds, action accelerates.', reversedMeaning: 'Delays, frustration, miscommunication, things stalling out.' },
  { id: 30, name: 'Nine of Wands',    arcana: 'minor', suit: 'wands', number: 9,  keywords: ['resilience', 'grit', 'last stand', 'wariness'], upright: 'Battle-worn but standing. One more push; your resilience is your strength.', reversedMeaning: 'Burnout, paranoia, refusing help, defensiveness that isolates.' },
  { id: 31, name: 'Ten of Wands',     arcana: 'minor', suit: 'wands', number: 10, keywords: ['burden', 'responsibility', 'overload', 'duty'], upright: 'Carrying too much. The weight of responsibility is real; consider what to set down.', reversedMeaning: 'Releasing burden, delegating, collapse from overload.' },
  { id: 32, name: 'Page of Wands',    arcana: 'minor', suit: 'wands', number: 11, keywords: ['curiosity', 'enthusiasm', 'discovery', 'free spirit'], upright: 'An eager beginner, a new interest pursued with bright enthusiasm.', reversedMeaning: 'Restlessness, lack of follow-through, immature enthusiasm.' },
  { id: 33, name: 'Knight of Wands',  arcana: 'minor', suit: 'wands', number: 12, keywords: ['adventure', 'impulsivity', 'passion', 'movement'], upright: 'Bold action, charging forward, passionate pursuit. Energy in motion.', reversedMeaning: 'Recklessness, burnout, anger, charging without a plan.' },
  { id: 34, name: 'Queen of Wands',   arcana: 'minor', suit: 'wands', number: 13, keywords: ['confidence', 'warmth', 'magnetism', 'independence'], upright: 'Self-assured warmth. A magnetic, confident presence that draws others in.', reversedMeaning: 'Insecurity, jealousy, demanding, scattered energy.' },
  { id: 35, name: 'King of Wands',    arcana: 'minor', suit: 'wands', number: 14, keywords: ['vision', 'leadership', 'boldness', 'entrepreneurship'], upright: 'Visionary leadership. Bold direction, charisma, the ability to rally others.', reversedMeaning: 'Domineering, impulsive leadership, ego, unrealized vision.' },

  // ===== CUPS (emotion, relationships, intuition, water) =====
  { id: 36, name: 'Ace of Cups',      arcana: 'minor', suit: 'cups', number: 1,  keywords: ['new feelings', 'love', 'openness', 'emotional beginnings'], upright: 'A wellspring of new emotion. Love, compassion, or creative feeling overflowing.', reversedMeaning: 'Emotional block, repressed feelings, an empty cup, closed heart.' },
  { id: 37, name: 'Two of Cups',      arcana: 'minor', suit: 'cups', number: 2,  keywords: ['partnership', 'connection', 'mutual respect', 'attraction'], upright: 'A balanced bond, mutual feeling, the meeting of two as equals.', reversedMeaning: 'Imbalance, broken connection, miscommunication, one-sided feelings.' },
  { id: 38, name: 'Three of Cups',    arcana: 'minor', suit: 'cups', number: 3,  keywords: ['friendship', 'celebration', 'community', 'joy'], upright: 'Joyful gathering, celebrating with people you love. Friendship as nourishment.', reversedMeaning: 'Isolation, gossip, social burnout, falling out with friends.' },
  { id: 39, name: 'Four of Cups',     arcana: 'minor', suit: 'cups', number: 4,  keywords: ['apathy', 'contemplation', 'discontent', 'missed opportunity'], upright: 'Disengagement, brooding, missing the offered cup because you are looking inward.', reversedMeaning: 'Reawakening interest, accepting what is offered, emerging from withdrawal.' },
  { id: 40, name: 'Five of Cups',     arcana: 'minor', suit: 'cups', number: 5,  keywords: ['loss', 'grief', 'regret', 'what remains'], upright: 'Grief over what was lost. Two cups still stand; mourn, but do not forget what remains.', reversedMeaning: 'Acceptance, moving on, forgiveness, finding meaning in loss.' },
  { id: 41, name: 'Six of Cups',      arcana: 'minor', suit: 'cups', number: 6,  keywords: ['nostalgia', 'childhood', 'memory', 'innocence'], upright: 'Sweet memory, reconnection with the past, a return of innocence or simplicity.', reversedMeaning: 'Stuck in the past, idealizing what was, refusing to grow up.' },
  { id: 42, name: 'Seven of Cups',    arcana: 'minor', suit: 'cups', number: 7,  keywords: ['choices', 'fantasy', 'illusion', 'options'], upright: 'Many options, some real, some fantasy. Discernment is required.', reversedMeaning: 'Clarity returning, choosing, cutting through illusion.' },
  { id: 43, name: 'Eight of Cups',    arcana: 'minor', suit: 'cups', number: 8,  keywords: ['walking away', 'seeking', 'disillusionment', 'moving on'], upright: 'Leaving behind what no longer fulfills, even if it looked good from outside.', reversedMeaning: 'Fear of leaving, returning to what you outgrew, indecision about going.' },
  { id: 44, name: 'Nine of Cups',     arcana: 'minor', suit: 'cups', number: 9,  keywords: ['satisfaction', 'wishes', 'contentment', 'pleasure'], upright: 'The wish card. Emotional satisfaction, your desires fulfilled.', reversedMeaning: 'Smugness, unfulfilled wishes, surface-level happiness over deeper lack.' },
  { id: 45, name: 'Ten of Cups',      arcana: 'minor', suit: 'cups', number: 10, keywords: ['harmony', 'family', 'fulfillment', 'lasting joy'], upright: 'Lasting emotional harmony. Family, home, the long-running joy of belonging.', reversedMeaning: 'Family conflict, broken harmony, the gap between idealized and real home life.' },
  { id: 46, name: 'Page of Cups',     arcana: 'minor', suit: 'cups', number: 11, keywords: ['sensitivity', 'creative messages', 'openness', 'playfulness'], upright: 'A tender, imaginative message. Emotional or creative inspiration arriving.', reversedMeaning: 'Emotional immaturity, blocked creativity, oversensitivity.' },
  { id: 47, name: 'Knight of Cups',   arcana: 'minor', suit: 'cups', number: 12, keywords: ['romance', 'idealism', 'offer', 'charm'], upright: 'A romantic offer, a heartfelt invitation, idealism in motion.', reversedMeaning: 'Moodiness, broken promises, unrealistic romance, charm without substance.' },
  { id: 48, name: 'Queen of Cups',    arcana: 'minor', suit: 'cups', number: 13, keywords: ['empathy', 'intuition', 'compassion', 'emotional wisdom'], upright: 'Deep emotional wisdom. Compassion held with steady, intuitive grace.', reversedMeaning: 'Emotional overwhelm, codependence, martyrdom, drowning in others\' feelings.' },
  { id: 49, name: 'King of Cups',     arcana: 'minor', suit: 'cups', number: 14, keywords: ['emotional balance', 'diplomacy', 'calm authority', 'compassion'], upright: 'Mastery of emotion. A calm, diplomatic presence under pressure.', reversedMeaning: 'Suppressed emotion, manipulation, volatility hidden behind calm.' },

  // ===== SWORDS (intellect, conflict, communication, air) =====
  { id: 50, name: 'Ace of Swords',    arcana: 'minor', suit: 'swords', number: 1,  keywords: ['clarity', 'breakthrough', 'truth', 'new idea'], upright: 'A piercing clarity, a breakthrough insight, the truth cutting through fog.', reversedMeaning: 'Confusion, miscommunication, truth withheld, mental block.' },
  { id: 51, name: 'Two of Swords',    arcana: 'minor', suit: 'swords', number: 2,  keywords: ['stalemate', 'indecision', 'avoidance', 'blocked feelings'], upright: 'A blindfolded standoff. A decision avoided; both options weigh equally.', reversedMeaning: 'Indecision breaking, information revealed, confusion clearing.' },
  { id: 52, name: 'Three of Swords',  arcana: 'minor', suit: 'swords', number: 3,  keywords: ['heartbreak', 'grief', 'painful truth', 'sorrow'], upright: 'A clean cut of pain. Heartbreak or hard truth, but the wound is honest.', reversedMeaning: 'Healing, releasing grief, forgiving, the worst of the pain passing.' },
  { id: 53, name: 'Four of Swords',   arcana: 'minor', suit: 'swords', number: 4,  keywords: ['rest', 'recovery', 'retreat', 'stillness'], upright: 'Necessary rest. Withdraw and recover; the battle will still be there.', reversedMeaning: 'Burnout, restlessness, refusing to rest, forced isolation.' },
  { id: 54, name: 'Five of Swords',   arcana: 'minor', suit: 'swords', number: 5,  keywords: ['hollow victory', 'conflict', 'ego', 'winning at a cost'], upright: 'Winning the fight but losing something more. Was it worth it?', reversedMeaning: 'Reconciliation, releasing resentment, walking away from a no-win fight.' },
  { id: 55, name: 'Six of Swords',    arcana: 'minor', suit: 'swords', number: 6,  keywords: ['transition', 'moving on', 'passage', 'leaving behind'], upright: 'Moving toward calmer waters. Leaving difficulty behind, even if reluctantly.', reversedMeaning: 'Resistance to change, unfinished business, unable to move on.' },
  { id: 56, name: 'Seven of Swords',  arcana: 'minor', suit: 'swords', number: 7,  keywords: ['deception', 'strategy', 'stealth', 'getting away with it'], upright: 'Cunning, strategy, or deception. Something taken, hidden, or worked around.', reversedMeaning: 'Confession, getting caught, returning what was taken, change of conscience.' },
  { id: 57, name: 'Eight of Swords',  arcana: 'minor', suit: 'swords', number: 8,  keywords: ['restriction', 'self-imposed limits', 'trapped thinking', 'victim mindset'], upright: 'Feeling trapped, but the binds are looser than they appear. Look more carefully.', reversedMeaning: 'Freeing yourself, seeing through limiting beliefs, releasing self-imposed restrictions.' },
  { id: 58, name: 'Nine of Swords',   arcana: 'minor', suit: 'swords', number: 9,  keywords: ['anxiety', 'nightmares', 'worry', 'mental anguish'], upright: 'Late-night anxiety, the catastrophizing mind. Often worse in your head than in fact.', reversedMeaning: 'Anxiety easing, hope returning, naming the fear and shrinking it.' },
  { id: 59, name: 'Ten of Swords',    arcana: 'minor', suit: 'swords', number: 10, keywords: ['rock bottom', 'ending', 'betrayal', 'defeat'], upright: 'The worst has happened. A definitive ending; from here, the only direction is up.', reversedMeaning: 'Recovery, refusing to be defeated, slow rise from the bottom.' },
  { id: 60, name: 'Page of Swords',   arcana: 'minor', suit: 'swords', number: 11, keywords: ['curiosity', 'vigilance', 'new ideas', 'sharp tongue'], upright: 'Mental curiosity, asking sharp questions, eager learning.', reversedMeaning: 'Gossip, scattered thinking, immature criticism, all talk.' },
  { id: 61, name: 'Knight of Swords', arcana: 'minor', suit: 'swords', number: 12, keywords: ['drive', 'directness', 'rushing', 'single-minded action'], upright: 'Charging headfirst toward a goal with focus and force.', reversedMeaning: 'Recklessness, aggression, burnout, charging in the wrong direction.' },
  { id: 62, name: 'Queen of Swords',  arcana: 'minor', suit: 'swords', number: 13, keywords: ['clarity', 'independence', 'honesty', 'discernment'], upright: 'Sharp-eyed honesty. Independent, perceptive, unsentimental wisdom.', reversedMeaning: 'Coldness, harsh judgment, bitterness, cutting words.' },
  { id: 63, name: 'King of Swords',   arcana: 'minor', suit: 'swords', number: 14, keywords: ['intellect', 'authority', 'ethics', 'clear judgment'], upright: 'Authority through clear thought. Ethical, principled, fair-minded leadership.', reversedMeaning: 'Manipulation, abuse of intellect, cold detachment, tyrannical reasoning.' },

  // ===== PENTACLES (material world, money, body, work, earth) =====
  { id: 64, name: 'Ace of Pentacles',     arcana: 'minor', suit: 'pentacles', number: 1,  keywords: ['opportunity', 'prosperity', 'new venture', 'manifestation'], upright: 'A tangible new opportunity. Money, work, or a project with real potential.', reversedMeaning: 'Missed opportunity, poor planning, scarcity mindset.' },
  { id: 65, name: 'Two of Pentacles',     arcana: 'minor', suit: 'pentacles', number: 2,  keywords: ['balance', 'juggling', 'adaptability', 'priorities'], upright: 'Juggling priorities with skill. Balance is possible, but it requires attention.', reversedMeaning: 'Overwhelm, dropping the ball, disorganization, financial strain.' },
  { id: 66, name: 'Three of Pentacles',   arcana: 'minor', suit: 'pentacles', number: 3,  keywords: ['collaboration', 'skill', 'craftsmanship', 'teamwork'], upright: 'Skilled collaboration. Each person\'s craft contributes to something greater.', reversedMeaning: 'Lack of teamwork, undervalued skill, working at cross-purposes.' },
  { id: 67, name: 'Four of Pentacles',    arcana: 'minor', suit: 'pentacles', number: 4,  keywords: ['holding on', 'security', 'control', 'scarcity'], upright: 'Holding tightly to what you have. Security, but at the cost of openness.', reversedMeaning: 'Loosening grip, generosity returning, financial loss, releasing control.' },
  { id: 68, name: 'Five of Pentacles',    arcana: 'minor', suit: 'pentacles', number: 5,  keywords: ['hardship', 'loss', 'exclusion', 'scarcity'], upright: 'Hard times. Material lack or feeling left out in the cold; help may be nearer than you think.', reversedMeaning: 'Recovery, accepting help, end of hardship, finding shelter.' },
  { id: 69, name: 'Six of Pentacles',     arcana: 'minor', suit: 'pentacles', number: 6,  keywords: ['generosity', 'giving and receiving', 'balance', 'support'], upright: 'Generosity flowing both ways. Resources shared in fair measure.', reversedMeaning: 'Strings attached, debt, imbalance in giving and receiving, charity as power.' },
  { id: 70, name: 'Seven of Pentacles',   arcana: 'minor', suit: 'pentacles', number: 7,  keywords: ['patience', 'long-term view', 'investment', 'assessment'], upright: 'Pause to assess what you\'ve been growing. Patience pays; the harvest takes time.', reversedMeaning: 'Impatience, poor returns, sunk cost, doubt about long efforts.' },
  { id: 71, name: 'Eight of Pentacles',   arcana: 'minor', suit: 'pentacles', number: 8,  keywords: ['craftsmanship', 'diligence', 'skill-building', 'focus'], upright: 'Heads-down work, mastering a craft through repetition and care.', reversedMeaning: 'Lack of focus, sloppy work, perfectionism, work without meaning.' },
  { id: 72, name: 'Nine of Pentacles',    arcana: 'minor', suit: 'pentacles', number: 9,  keywords: ['self-sufficiency', 'luxury', 'earned comfort', 'independence'], upright: 'Earned comfort and self-sufficiency. The fruit of long discipline, enjoyed alone.', reversedMeaning: 'Financial setback, dependency, hollow luxury, isolation in success.' },
  { id: 73, name: 'Ten of Pentacles',     arcana: 'minor', suit: 'pentacles', number: 10, keywords: ['legacy', 'wealth', 'family', 'long-term security'], upright: 'Long-term wealth, legacy, the security that extends across generations.', reversedMeaning: 'Family conflict over resources, financial instability, broken legacy.' },
  { id: 74, name: 'Page of Pentacles',    arcana: 'minor', suit: 'pentacles', number: 11, keywords: ['learning', 'ambition', 'new skill', 'studious'], upright: 'Earnest beginner, a new skill or venture pursued with diligence.', reversedMeaning: 'Procrastination, lack of progress, missed opportunities to start.' },
  { id: 75, name: 'Knight of Pentacles',  arcana: 'minor', suit: 'pentacles', number: 12, keywords: ['routine', 'reliability', 'perseverance', 'methodical'], upright: 'Steady, methodical progress. Boring on the surface, deeply effective underneath.', reversedMeaning: 'Stagnation, stubbornness, boredom, work without progress.' },
  { id: 76, name: 'Queen of Pentacles',   arcana: 'minor', suit: 'pentacles', number: 13, keywords: ['nurture', 'practicality', 'abundance', 'groundedness'], upright: 'Grounded nurturing. Practical care for home, body, work, and the people around you.', reversedMeaning: 'Self-neglect, work-life imbalance, smothering, materialism.' },
  { id: 77, name: 'King of Pentacles',    arcana: 'minor', suit: 'pentacles', number: 14, keywords: ['abundance', 'stability', 'mastery', 'generous wealth'], upright: 'Mastery of the material world. Stable, generous, the steady provider.', reversedMeaning: 'Greed, materialism, financial mismanagement, status over substance.' },
];

// Suit symbols for display
export const SUIT_SYMBOL: Record<string, string> = {
  major:     '✦',
  wands:     '↑',
  cups:      '∪',
  swords:    '✕',
  pentacles: '◆',
};

// Draw N unique cards, each with a random orientation.
export function drawCards(n = 3): DrawnCard[] {
  const shuffled = [...cards].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, n).map(card => ({
    ...card,
    isReversed: Math.random() < 0.5,
  }));
}
